{
  "BLC": 1,
  "Bitembois": 1,
  "Dieu me pignole": 1,
  "Dieu me tripote": 1,
  "FDP": 4,
  "NTM": 4,
  "PD": 3,
  "TG": 1,
  "VDM": 1,
  "aller aux putes": 2,
  "aller niquer sa mère": 4,
  "aller se faire enculer": 4,
  "aller se faire foutre": 1,
  "aller se faire mettre": 4,
  "allez vous faire foutre": 1,
  "archifoutre": 1,
  "avoir de la chatte": 1,
  "avoir des couilles": 1,
  "avoir des couilles au cul": 1,
  "avoir du cul": 1,
  "avoir du poil au cul": 1,
  "avoir la gueule dans le cul": 1,
  "avoir la tête dans le cul": 1,
  "avoir le cul bordé de médailles": 1,
  "avoir le cul bordé de nouilles": 1,
  "avoir le feu au cul": 1,
  "avoir le papier qui colle aux bonbons": 1,
  "avoir le trou du cul en chou-fleur": 1,
  "avoir les couilles": 1,
  "avoir les yeux en trou de bite": 1,
  "avoir les yeux en trou de pine": 1,
  "avoir l’air con": 1,
  "avoir plein le cul": 1,
  "avoir un balai dans le cul": 1,
  "baisable": 4,
  "baise": 4,
  "baiser": 4,
  "baiser Fanny": 4,
  "baiser comme des lapins": 4,
  "baiser comme un lapin": 4,
  "baiseur": 4,
  "bander": 2,
  "bander comme un Turc": 2,
  "bander comme un cerf": 2,
  "bander comme un taureau": 2,
  "bander comme un âne": 2,
  "bar à putes": 2,
  "bibite": 1,
  "bitch": 2,
  "bite": 1,
  "bonasse": 1,
  "bonnasse": 1,
  "bordel": 1,
  "bordel de merde": 1,
  "bordel à cul": 1,
  "bordel à cul de pompe à merde": 1,
  "bordel à cul pompe à merde": 1,
  "botter le cul": 1,
  "bouffer la chatte": 2,
  "bouffer le cul": 2,
  "boule": 1,
  "branle-couille": 1,
  "branler": 1,
  "branler le mammouth": 1,
  "branlette": 1,
  "branlette espagnole": 1,
  "branlette intellectuelle": 1,
  "branleur": 1,
  "branlotter": 1,
  "brise-burnes": 1,
  "brouter les couilles": 1,
  "casse-couille": 1,
  "casse-couilles": 1,
  "casser la gueule": 1,
  "casser les boules": 1,
  "casser les burnes": 1,
  "casser les couilles": 1,
  "chacun sa merde": 1,
  "chagasse": 2,
  "chat bite": 1,
  "chat-bite": 1,
  "cherche-merde": 1,
  "chiant": 1,
  "chiant comme la Lune": 1,
  "chiasse": 1,
  "chiasser": 1,
  "chiatique": 1,
  "chier": 1,
  "chier comme tout le monde": 1,
  "chier dans les bottes": 1,
  "chier dans son froc": 1,
  "chier pour la marine": 1,
  "chier une pendule": 1,
  "chieur": 1,
  "claque merde": 1,
  "claque-merde": 1,
  "comme papa dans maman": 4,
  "comme un chien fout sa merde": 1,
  "con": 2,
  "con comme un balai": 2,
  "con comme un gland": 2,
  "con comme une bite": 2,
  "connard": 3,
  "connarde": 3,
  "connasse": 3,
  "connerie": 1,
  "copain de baise": 2,
  "copine de baise": 2,
  "couille": 1,
  "couille de loup": 1,
  "couille molle": 1,
  "couilles au poteau": 1,
  "coup de pute": 1,
  "couter la peau des couilles": 1,
  "couter la peau du cul": 1,
  "coûter la peau des couilles": 1,
  "coûter la peau du cul": 1,
  "coûter une couille": 1,
  "cul": 1,
  "c’est de la couille de loup": 1,
  "dans ton cul": 1,
  "de mes couilles": 1,
  "de mes deux": 1,
  "des couilles": 1,
  "ducon": 1,
  "duconnot": 1,
  "dugland": 1,
  "déconnade": 1,
  "déconnage": 1,
  "déconner": 1,
  "décrisser": 1,
  "démerde yourself": 1,
  "emmerder": 4,
  "emmerdeur": 3,
  "emmerdé": 4,
  "en avoir plein le cul": 1,
  "en avoir plein les couilles": 1,
  "en avoir ras les burnes": 1,
  "en chier": 1,
  "encuguler": 3,
  "enculable": 4,
  "enculade": 4,
  "enculade de mouche": ,
  "enculagailler": 4,
  "enculage": 4,
  "enculage de mouche": 4,
  "enculage de mouches": 4,
  "enculailleur": 4,
  "enculatoire": 4,
  "enculement": 4,
  "enculer": 4,
  "enculer les mouches": 4,
  "enculerie": 4,
  "enculette": 4,
  "enculeur": 4,
  "enculeur de mouches": 4,
  "enculeuse": 4,
  "enculé": 4,
  "enculé de ta mère": 4,
  "enculé de ta race": 4,
  "enfant de chienne": 4,
  "enfant de putain": 4,
  "enfant de pute": 4,
  "enfoirer": 3,
  "enfoiré": 3,
  "engueuler": 1,
  "entre couilles": 1,
  "envoyer chier": 1,
  "et mon cul, c’est du poulet": 1,
  "et ta connerie": 1,
  "faire chier": 1,
  "faire chier la bite": 1,
  "faire sa pute": 2,
  "ferme ta gueule": 1,
  "fermer sa gueule": 1,
  "fermer son claque merde": 1,
  "fermer son claque-merde": 1,
  "fille à pédés": 4,
  "film de boule": 1,
  "film de boules": 1,
  "fils de bâtard": 4,
  "fils de chien": 4,
  "fils de chienne": 4,
  "fils de garce": 4,
  "fils de putain": 4,
  "fils de pute": 4,
  "fils de ta race": 4,
  "fils-de-puterie": 3,
  "filsdeputerie": 3,
  "fouille-merde": 1,
  "foutage de gueule": 1,
  "fouteur de merde": 1,
  "foutre": 1,
  "foutre la merde": 1,
  "foutre sur la gueule": 1,
  "fuck": 4,
  "fuck me boots": 4,
  "fucker": 4,
  "garage à bite": 1,
  "garage à bites": 1,
  "gland": 1,
  "gueule": 1,
  "gueuler": 1,
  "imbaisable": 3,
  "langue de pute": 2,
  "le con de sa mère": 1,
  "lèche-cul": 1,
  "lécher le cul": 2,
  "l’avoir dans le cul": 1,
  "manche à couilles": 1,
  "mange-merde": 1,
  "manger de la marde": 1,
  "merdasse": 1,
  "merde": 1,
  "merder": 1,
  "merderie": 1,
  "merdeux": 1,
  "merdier": 1,
  "mes couilles": 1,
  "mes couilles le temps se brouille": 1,
  "mettre ses couilles sur la table": 1,
  "mettre sur la gueule": 1,
  "mon cul": 1,
  "ne plus se sentir pisser": 1,
  "ne rien branler": 1,
  "nique sa mère": 4,
  "nique ta mère": 4,
  "niquer": 4,
  "niquer sa mère": 4,
  "nul à chier": 1,
  "n’en avoir rien à foutre": 1, -
  "oh hisse, enculé": 4,
  "on s’encule": 4,
  "oui ou merde": 1,
  "ouvrir sa grande gueule": 1,
  "parle à mon cul, ma tête est malade": 1,
  "partir en couille": 1,
  "pelle à merde": 1,
  "penser avec sa bite": 1,
  "plan cul": 1,
  "pomper": 2,
  "porc": 2,
  "putain": 1,
  "putain con": 1,
  "putain de": 1,
  "putain de bordel de merde": 1,
  "putain de merde": 1,
  "putain de moine": 1,
  "putain de sa mère": 1,
  "putain de sa race": 1,
  "putain de ta race": 1,
  "pute": 2,
  "pute borgne": 2,
  "pute de luxe": 2,
  "pédé": 1,
  "pédé comme un Grec": 1,
  "qu’il aille se faire foutre": 1,
  "qu’ils aillent se faire foutre": 1,
  "qu’on l’encule": 4,
  "raccrocher à la gueule": 1,
  "ras le cul": 1,
  "refucker": 4,
  "remuer la merde": 1,
  "rien à enculer": 4,
  "rien à foutre": 1,
  "roubignole": 1,
  "réenculer": 4,
  "sac à merde": 1,
  "salaud": 2,
  "salopard": 2,
  "salope": 2,
  "sans-couilles": 1,
  "se battre les couilles de": 1,
  "se branler comme de l’an quarante de": 2,
  "se branler les couilles": 2,
  "se casser la gueule": 1,
  "se casser le cul": 1,
  "se casser les couilles": 1,
  "se doigter": 4,
  "se faire enculer": 4,
  "se faire la bite": 4,
  "se faire pousser au cul": 1,
  "se foutre de": 1,
  "se foutre de la gueule de": 1,
  "se geler le fion": 1,
  "se geler les couilles": 1,
  "se magner le cul": 1, 
  "se vider les couilles": 1,
  "sous-merde": 1,
  "suce-boules": 3,
  "suce-médailles": 2,
  "sucer": 2,
  "suceuse": 2,
  "s’archifoutre": 1,
  "s’en badigeonner les testicules avec le pinceau de l’indifférence": 1,
  "s’en branler": 2,
  "ta gueule": 1,
  "ta mère la pute": 4,
  "teub": 1,
  "tg": 1,
  "tire-au-cul": 1,
  "touche à ton cul t’auras des verrues": 1,
  "tout de la gueule": 1,
  "trou de balle": 1,
  "trou de cul": 1,
  "trou du cul": 1,
  "trou du cul du monde": 1,
  "trouduc": 1,
  "trouducune": 1,
  "trouer le cul": 1,
  "tête de gland": 1,
  "va chier": 1,
  "va niquer ta mère": 4,
  "va te faire enculer": 4,
  "va te faire foutre": 1,
  "va te faire mettre": 4,
  "vtff": 1,
  "yeule": 1,
  "zboob": 1,
  "zboube": 1,
  "zguègue": 1,
  "à chier": 1,
  "à couilles rabattues": 1,
  "à la con": 1,
  "à la roule-moi les couilles dans la laitue": 1,
  "à un poil de cul": 1,
  "écouillé": 1,
  "être chié": 1,
  "être mou de la bite": 1
}